spring:
  application.name: chat-bot
  kafka.bootstrap-servers: 35.239.109.122:9094
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5430/chat-bot


telegram.bot:
    token: 8105529885:AAHIZb1ztjaN1aKExOS79bCec1l4fUQLdrI
      username: PhoneLowPriceFinderBot

grpc.client.productService:
  address: 'static://localhost:9090'
  negotiation-type: plaintext




